### ISSUE TITLE
Did you try your collabora setup?

### ISSUE THREAD

**Issue by pierreozoux** [SnowMB/nextcloud#3]
I think it doesn't work :)

**Comment by SnowMB** [comment]
I'm running it myself. What's the problem?

**Comment by pierreozoux** [comment]
I had an issue because it was not on the same domain name...
You have 2 domain names right?
One for cloud and one for office, and no issues?

**Comment by SnowMB** [comment]
Yeah I use cloud.mydomain.tld and office.mydomain.tld
