### ISSUE TITLE
Collabora: Connection refused

### ISSUE THREAD

**Issue by rwlloyd** [SnowMB/nextcloud#6]
I get this error when trying to connect to the office app.

``
Collabora Online: Cannot connect to the host "https://localhost:9980".
Please ask your administrator to check the Collabora Online server setting. The exact error message was: cURL error 7: Failed to connect to localhost port 9980: Connection refused
``

Initially, I thought it might be that I needed the port open on my router. However, no luck. Apart from that, everything is working perfectly. 

The only mentions of this error online are suggesting that it might be an issue with the reverse proxy or a php file somewhere. But I'm pretty new to all this so I'm just parroting back what I read.

Apart from that everything seems perfect, excellent work, thank you.

**Comment by SnowMB** [comment]
Hey,

Have you changed the collabora url in the admin / settings (additional settings) page? 

It should look like this: 

![unbenannt](https://cloud.githubusercontent.com/assets/7050959/20925885/cba8c180-bbb9-11e6-90bd-bb2ff61edcf8.png)



Use no port number!

**Comment by rwlloyd** [comment]
Ha! easy when you know how. That's perfect now! again, thanks very much.
